app_group:
  - read:
      path: /apps/prom.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}/_topology
      method: POST

patch:
  - update:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.prom.v1alpha1.export:
  - create:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports
      method: POST
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}
      method: GET
  - update:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}
      method: PUT

com.nokia.eda.prom.v1alpha1.export_list:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports
      method: GET
  - delete:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports
      method: DELETE

com.nokia.eda.prom.v1alpha1.export_deleted_resources:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/_deleted
      method: GET

totalPaths: 9
totalSchemas: 54
usedSchemas: 12
unusedSchemas: 42
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - com.nokia.eda.prom.v1alpha1.Export_DeletedResourceEntry
  - com.nokia.eda.prom.v1alpha1.Export_alarms
  - com.nokia.eda.prom.v1alpha1.Export_deviations
  - com.nokia.eda.prom.v1alpha1.Export_metadata
