app_group:
  - read:
      path: /apps/prom.eda.nokia.com
      method: GET

patch:
  - update:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.prom.v1alpha1.export:
  - create:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports
      method: POST
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}
      method: GET
  - update:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/{name}
      method: PUT

com.nokia.eda.prom.v1alpha1.export_list:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports
      method: GET
  - delete:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports
      method: DELETE

com.nokia.eda.prom.v1alpha1.export_deleted_resources:
  - read:
      path: /apps/prom.eda.nokia.com/v1alpha1/exports/_deleted
      method: GET

totalPaths: 8
totalSchemas: 33
usedSchemas: 10
unusedSchemas: 23
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoElemMetadata
  - TopoLinkEndpoint
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeState
  - TopoSchema
  - Topology
  - com.nokia.eda.prom.v1alpha1.Export_DeletedResourceEntry
  - com.nokia.eda.prom.v1alpha1.Export_metadata
